"""empty message

Revision ID: 25f72f9c6a79
Revises: 
Create Date: 2022-06-30 03:55:18.701404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f72f9c6a79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Descuento',
    sa.Column('id_descuento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('porcentaje', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_descuento')
    )
    op.create_table('Region',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_region')
    )
    op.create_table('Registro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=250), nullable=False),
    sa.Column('primer_apellido', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario_car',
    sa.Column('id_car', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=250), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=250), nullable=False),
    sa.Column('apellido_materno', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.Column('fono', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_car')
    )
    op.create_table('despacho',
    sa.Column('id_despacho', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('hora_entrega', sa.Date(), nullable=True),
    sa.Column('rut_recibe', sa.String(length=10), nullable=True),
    sa.Column('nombre_recibe', sa.String(length=250), nullable=True),
    sa.Column('esto_despacho', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['Comuna.id_comuna'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_despacho'),
    sa.UniqueConstraint('rut_recibe')
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('valor_venta', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('producto_carrito',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('valor_venta', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=True),
    sa.Column('sub_total', sa.Integer(), nullable=False),
    sa.Column('iva', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('despacho_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Usuario.id'], ),
    sa.ForeignKeyConstraint(['despacho_id'], ['despacho.id_despacho'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id_vendedor'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('Provincias',
    sa.Column('id_prov', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['Region.id_region'], ),
    sa.PrimaryKeyConstraint('id_prov')
    )
    op.create_table('descuento_producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('descuento_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_termino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['descuento_id'], ['Descuento.id_descuento'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('Comuna',
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provincia_id'], ['Provincias.id_prov'], ),
    sa.PrimaryKeyConstraint('id_comuna')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=250), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=250), nullable=False),
    sa.Column('apellido_materno', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=True),
    sa.Column('fono', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['Comuna.id_comuna'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendedor',
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=9), nullable=False),
    sa.Column('dv', sa.String(length=1), nullable=False),
    sa.Column('primer_nombre', sa.String(length=250), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=250), nullable=False),
    sa.Column('apellido_materno', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('fono', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['Comuna.id_comuna'], ),
    sa.PrimaryKeyConstraint('id_vendedor'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('donacion',
    sa.Column('id_donacion', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id_donacion')
    )
    op.create_table('suscripcion',
    sa.Column('id_suscripcion', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_termino', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id_suscripcion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suscripcion')
    op.drop_table('donacion')
    op.drop_table('vendedor')
    op.drop_table('Usuario')
    op.drop_table('Comuna')
    op.drop_table('detalle')
    op.drop_table('descuento_producto')
    op.drop_table('Provincias')
    op.drop_table('venta')
    op.drop_table('producto_carrito')
    op.drop_table('producto')
    op.drop_table('despacho')
    op.drop_table('Usuario_car')
    op.drop_table('Registro')
    op.drop_table('Region')
    op.drop_table('Descuento')
    # ### end Alembic commands ###
