"""empty message

Revision ID: 47b83cb6dedb
Revises: 25f72f9c6a79
Create Date: 2022-06-30 23:51:36.793758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b83cb6dedb'
down_revision = '25f72f9c6a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Registro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Registro',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('correo', sa.VARCHAR(length=250), nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), nullable=True),
    sa.Column('estado', sa.INTEGER(), nullable=False),
    sa.Column('primer_nombre', sa.VARCHAR(length=250), nullable=False),
    sa.Column('primer_apellido', sa.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
