"""empty message

Revision ID: 52c3be9fddaf
Revises: abaa91f18164
Create Date: 2022-06-10 05:18:01.565091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c3be9fddaf'
down_revision = 'abaa91f18164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descuento_producto', sa.Column('fecha_inicio', sa.Date(), nullable=False))
    op.add_column('descuento_producto', sa.Column('fecha_termino', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('descuento_producto', 'fecha_termino')
    op.drop_column('descuento_producto', 'fecha_inicio')
    # ### end Alembic commands ###
