"""empty message

Revision ID: 5bf1daa10601
Revises: 8ecded4a4792
Create Date: 2022-06-10 04:36:15.792967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf1daa10601'
down_revision = '8ecded4a4792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Region',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_region')
    )
    op.create_table('Comuna',
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('Region_id_region', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Region_id_region'], ['Region.id_region'], ),
    sa.PrimaryKeyConstraint('id_comuna')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comuna')
    op.drop_table('Region')
    # ### end Alembic commands ###
