"""empty message

Revision ID: abaa91f18164
Revises: 5bf1daa10601
Create Date: 2022-06-10 05:13:21.559374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abaa91f18164'
down_revision = '5bf1daa10601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Descuento',
    sa.Column('id_descuento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('porcentaje', sa.Float(precision=3), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_descuento')
    )
    op.create_table('descuento_producto',
    sa.Column('producto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descuento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['descuento_id'], ['Descuento.id_descuento'], ),
    sa.PrimaryKeyConstraint('producto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('descuento_producto')
    op.drop_table('Descuento')
    # ### end Alembic commands ###
